title: Cécile Ricordeau
baseurl: https://www.cecillie.fr/
baseline: Direction artistique, UI design, illustration
description: Cécile Ricordeau, directrice artistique freelance à Paris, experte en UI design et illustratrice.
image: icon.png
author:
  firstname: Cécile
  lastname: Ricordeau
  url: https://www.cecillie.fr
  email: hello@cecillie.fr
social:
  instagram:
    url: https://www.instagram.com/cecile.ricordeau/
  linkedin:
    url: https://www.linkedin.com/in/cecile-ricordeau/
  twitter:
    site: onibd
  bluesky:
    url: https://bsky.app/profile/cecillie.bsky.social
  mastodon:
    url: https://eldritch.cafe/@cecillie
links:
  - name: Instagram
    url: https://www.instagram.com/cecile.ricordeau/
  - name: Linkedin
    url: https://www.linkedin.com/in/cecile-ricordeau/
  - name: Blog
    url: /blog/
    blank: false
  - name: Shop
    url: https://shop.cecillie.fr
#  - name: Twitter
#    url: https://www.twitter.com/onibd
#  - name: Medium
#    url: https://medium.com/@cecile.ricordeau
#  - name: Behance
#    url: https://www.behance.net/cecillie
#  - name: Vimeo
#    url: https://vimeo.com/cecillie
#  - name: Book
#    url: http://bitly.com/cecillie
#  - name: CV
#    url: "/cecile-ricordeau-cv.pdf"
#    blank: false
#  - name: hello[at]cecillie.fr
#    url: mailto:hello@cecillie.fr
#    blank: false
language: fr
languages:
  - code: fr
    name: Français
    locale: fr
  - code: en
    name: English
    locale: en
    config:
      baseline: Art direction, UI design, illustration
      description: Cécile Ricordeau, freelance art director, ui design expert, illustrator.
      links:
        - name: Instagram
          url: https://www.instagram.com/cecile.ricordeau/
        - name: Linkedin
          url: https://www.linkedin.com/in/cecile-ricordeau/?locale=en_US
        #- name: Shop
        #  url: https://shop.cecillie.fr/en/
metatags:
  jsonld: true
pages:
  body:
    images:
      caption: true
      resize: true
      responsive: true
      webp: true
assets:
  images:
    optimize: true
    responsive: true
    webp: true
theme:
  - netlify
netlify:
  redirects:
    - from: https://cecillie.netlify.com/*
      to: https://cecillie.fr/:splat
      status: 301
      force: true
  redirect_by_language: false
