title: Cécile Ricordeau
baseurl: https://www.cecillie.fr/
baseline: Art direction, UI design, illustration
description: Cécile Ricordeau, freelance art director, ui design expert, illustrator.
image: /img/twitter-card.png
author:
  firstname: Cécile
  lastname: Ricordeau
  url: https://www.cecillie.fr
  email: hello@cecillie.fr
language: en
languages:
  - code: en
    name: English
    locale: en_US
  - code: fr
    enabled: false
    name: Français
    locale: fr_FR
    config:
      baseline: Direction artistique, UI design, illustration
      description: Cécile Ricordeau, directrice artistique freelance à Paris, experte en UI design et illustratrice.
links:
- name: Instagram
  url: https://www.instagram.com/cecile.ricordeau/
- name: Behance
  url: https://www.behance.net/cecillie
#- name: Vimeo
#  url: https://vimeo.com/cecillie
- name: Linkedin
  url: https://www.linkedin.com/in/digitalcreation/
#- name: Twitter
#  url: https://www.twitter.com/onibd
- name: Medium
  url: https://medium.com/@cecile.ricordeau
- name: Shop
  url: https://shop.cecillie.fr/
#- name: Book
#  url: http://bitly.com/cecillie
#- name: CV
#  url: "/cecile-ricordeau-cv.pdf"
#- name: hello[at]cecillie.fr
#  url: mailto:hello@cecillie.fr
defaultpages:
  sitemap:
    published: true
theme:
  - netlify
netlify:
  redirects:
    - from: https://cecillie.netlify.com/*
      to: https://cecillie.fr/:splat
      status: 301
      force: true

body:
  images:
    lazy:
      enabled: true
    caption:
      enabled: true
    resize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
