[build]
  publish = "_site"
  command = "bash ./scripts/netlify-build.sh"

[build.environment]
  PHP_VERSION = "7.4"
  NODE_VERSION = "12.16"
  CECIL_ENV = "production"
  CECIL_CACHE_DIR = "/opt/build/cache/"
  CSS_INPUT = "assets/tailwind.css"
  CSS_OUPUT = "assets/styles.css"

[context.production.environment]
  CECIL_ENV = "production"

[context.deploy-preview.environment]
  CECIL_ENV = "preview"
