[build]
  publish = "_site"
  command = "chmod +x ./scripts/netlify-build.sh && bash ./scripts/netlify-build.sh"
[build.environment]
  NODE_VERSION = "12.16"
  CSS_INPUT = "static/tailwind.css"
  CSS_OUPUT = "static/styles.css"

[context.deploy-preview.environment]
  CECIL_ENV = "preview"

[context.branch-deploy.environment]
  CECIL_ENV = "branch"
